
FROM python:3.8.10
LABEL maintainer = "mudokja@gmail.com"

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
RUN apt-get update && apt-get install libgl1 -y
RUN apt-get update && apt-get install -y default-jdk
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install --no-cache-dir uvicorn

COPY . /code
EXPOSE 3333

CMD ["uvicorn", "server:app", "--port", "3333","--host","0.0.0.0","--log-level","error","--proxy-headers","--forwarded-allow-ips","*"]
#CMD ["gunicorn", "--workers=4", "-k","uvicorn.workers.UvicornWorker","-t","240","--bind=0.0.0.0:3333", "server:app", "--forwarded-allow-ips","*"]
