FROM azul/zulu-openjdk-alpine:17
LABEL maintainer = "mudokja@gmail.com"

ARG DEFAULT_PORT=8082
ARG JAR_FILE=build/libs/*.jar
ARG DEFAULT_BACKEND_BASEURL=http://localhost

COPY ${JAR_FILE} /app/backend-api.jar

ENV PORT ${DEFAULT_PORT}
ENV BACKEND_BASEURL ${DEFAULT_BACKEND_BASEURL}

EXPOSE $PORT

ENTRYPOINT ["java", "-jar", "/app/backend-api.jar"]